{
  return getCause() instanceof java.io.IOException;
}
